services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - $PWD/pv/data:/opt/keycloak/data/h2
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

  web:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-amd64
    ports:
      - 80:4180
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxx
      OAUTH2_PROXY_REDIRECT_URL: http://localhost/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/realms/sample-realm
      OAUTH2_PROXY_COOKIE_SECRET: "uia75dtyfqw9q7yqihwdq6t7wd9nq3e3"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_UPSTREAMS: http://web/
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_BANNER: "Login with Keycloak to access nginx web server"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
